apiVersion: v1
kind: Service
metadata:
  labels:
    app: ducta11-kubernetes-udagram-api-user
  name: ducta11-kubernetes-udagram-api-user-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ducta11-kubernetes-udagram-api-user-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ducta11-kubernetes-udagram-api-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
